name: Build and Release EXE

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.3.0)'
        required: true
        default: 'v0.2.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies (PyInstaller)
      run: |
        pip install pyinstaller PyQt6 # Upewnij się, że PyQt6 jest zainstalowane

    - name: Get Build Version
      id: get_build_version
      shell: bash
      run: |
        BASE_VERSION="${{ github.event.inputs.version }}"
        BUILD_NUMBER="${{ github.run_number }}"
        FULL_VERSION="${BASE_VERSION}.${BUILD_NUMBER}"
        echo "Release tag will be: $FULL_VERSION"
        echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT

    - name: Create version.txt dynamically
      shell: bash
      run: |
        version="${{ steps.get_build_version.outputs.full_version }}"
        ver_nums=$(echo "$version" | sed 's/^v//' | awk -F. '{printf "%d, %d, %d, %d", $1, $2, $3, $4}')

        echo "VSVersionInfo(" > version.txt
        echo "  ffi=FixedFileInfo(" >> version.txt
        echo "    filevers=($ver_nums)," >> version.txt
        echo "    prodvers=($ver_nums)," >> version.txt
        echo "    mask=0x3f," >> version.txt
        echo "    flags=0x0," >> version.txt
        echo "    OS=0x40004," >> version.txt
        echo "    fileType=0x1," >> version.txt
        echo "    subtype=0x0," >> version.txt
        echo "    date=(0, 0)" >> version.txt
        echo "  )," >> version.txt
        echo "  kids=[" >> version.txt
        echo "    StringFileInfo([" >> version.txt
        echo "      StringTable(" >> version.txt
        echo "        '040904B0'," >> version.txt
        echo "        [" >> version.txt
        echo "          StringStruct('CompanyName', 'RichRichie')," >> version.txt
        echo "          StringStruct('FileDescription', 'UOCrafter GUI Tool')," >> version.txt
        echo "          StringStruct('FileVersion', '$version')," >> version.txt
        echo "          StringStruct('InternalName', 'UOCrafter')," >> version.txt
        echo "          StringStruct('OriginalFilename', 'UOCrafter.exe')," >> version.txt
        echo "          StringStruct('ProductName', 'UOCrafter Crafting Assistant')," >> version.txt
        echo "          StringStruct('ProductVersion', '$version')" >> version.txt
        echo "        ]" >> version.txt
        echo "      )" >> version.txt
        echo "    ])," >> version.txt
        echo "    VarFileInfo([VarStruct('Translation', [1033, 1200])])" >> version.txt
        echo "  ]" >> version.txt
        echo ")" >> version.txt

    - name: Build executable with PyInstaller (onedir)
      shell: bash # <--- DODANO TĘ LINIĘ
      run: |
        pyinstaller --onedir --windowed --icon=icon.ico --version-file=version.txt UOCrafter.py \
        --hidden-import=PyQt6.QtCore \
        --hidden-import=PyQt6.QtWidgets \
        --hidden-import=PyQt6.QtGui

    - name: Create ZIP archive
      shell: bash
      run: |
        VERSION="${{ steps.get_build_version.outputs.full_version }}"
        BUILD_DIR="dist/UOCrafter_work" 
        ZIP_FILE="UOCrafter-${VERSION}.zip"
        
        # Przechodzimy do katalogu z buildem
        cd "${BUILD_DIR}"
        "C:/Program Files/7-Zip/7z.exe" a -tzip "${GITHUB_WORKSPACE}/${ZIP_FILE}" ./*

    - name: List files in root directory for debugging
      run: ls -l
      shell: bash

    - name: Create GitHub Release and Upload ZIP
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_build_version.outputs.full_version }}
        name: "UOCrafter ${{ steps.get_build_version.outputs.full_version }}"
        draft: false
        prerelease: false
        files: UOCrafter-${{ steps.get_build_version.outputs.full_version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}